// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/tomkdickinson/serverless-go-template/internal/api"
	"github.com/tomkdickinson/serverless-go-template/internal/blog"
	"github.com/tomkdickinson/serverless-go-template/internal/storage/memory"
)

// Injectors from inject_main.go:

func setupHandler() api.BlogPostHandlers {
	repository := memory.ProvideRepository()
	service := blog.ProvideService(repository)
	blogPostHandlers := api.ProvideBlogPostHandlers(service)
	return blogPostHandlers
}
