// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tomkdickinson/serverless-hexagonal-go/internal/blog"
	"github.com/tomkdickinson/serverless-hexagonal-go/internal/lambda"
	"github.com/tomkdickinson/serverless-hexagonal-go/internal/storage/memory"
)

// Injectors from inject_main.go:

func setupHandler() lambda.BlogPostHandlers {
	repository := memory.ProvideRepository()
	service := blog.ProvideService(repository)
	blogPostHandlers := lambda.ProvideBlogPostHandlers(service)
	return blogPostHandlers
}
